name = "api"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MARKET_CACHE"
id = "122c51ef34e540fabb07f7939b1e01b6"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
