export const STRATEGY_COLORS = { bullish: "var(--green)", bearish: "var(--red)", neutral: "var(--amber)" };

export function ordinalSuffix(n) {
  if (n % 100 >= 11 && n % 100 <= 13) return "th";
  switch (n % 10) {
    case 1: return "st";
    case 2: return "nd";
    case 3: return "rd";
    default: return "th";
  }
}

export function impactClass(impact) {
  if (!impact) return "impact-low";
  const k = impact.replace(/\s+/g, "-").toLowerCase();
  if (k === "action-required") return "impact-action";
  if (k === "critical") return "impact-critical";
  if (k === "moderate") return "impact-moderate";
  return "impact-low";
}

export function impactDotColor(impact) {
  if (!impact) return "var(--t3)";
  const k = impact.replace(/\s+/g, "-").toLowerCase();
  if (k === "critical") return "var(--red)";
  if (k === "moderate") return "var(--amber)";
  if (k === "action-required") return "var(--navy)";
  return "var(--t3)";
}

export function formatTradeAsMarkdown(trade, marketContext, analysedAt) {
  const { summary, exitStrategy, predictions, greeks, rationale, riskFactors, strategyRationale, watchFor } = trade;
  const isSpread = !!trade.strike2;
  const strikeDisplay = isSpread ? `$${trade.strike} / $${trade.strike2}` : `$${trade.strike}`;
  const ivNum = parseInt(trade.ivRank, 10) || 0;
  const dateStr = analysedAt
    ? analysedAt.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) +
      " at " + analysedAt.toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" })
    : "";

  const lines = [
    `# ${trade.ticker} — ${trade.strategy}`,
    `> Options Advisor recommendation${dateStr ? ` · ${dateStr}` : ""}`,
    "",
    `**Conviction:** ${summary.conviction} (${summary.confidenceScore}%) · **Risk:** ${trade.riskLevel}/5`,
    "",
    "## Position",
    "| | |",
    "|---|---|",
    `| Strike | ${strikeDisplay} |`,
    `| Expiry | ${trade.expiryLabel} (${trade.daysToExpiry}d) |`,
    `| Entry | $${trade.entryPrice}/contract · ${trade.totalCost} total |`,
    `| Stock price | $${trade.currentPrice} |`,
    `| Break-even | $${trade.breakeven} |`,
    `| Max profit | ${trade.maxProfit} |`,
    `| Max loss | ${trade.maxLoss} |`,
    `| IV rank | ${trade.ivRank}${ordinalSuffix(ivNum)} percentile |`,
    "",
    "## Summary",
    `**${summary.headline}**`,
    "",
    summary.plainEnglish,
    "",
    `*When to sell: ${summary.whenToSellSimple}*`,
  ];

  if (strategyRationale) {
    lines.push("", "## Why this strategy", strategyRationale);
  }

  lines.push(
    "",
    "## Exit rules",
    `- 🟢 **Take profit:** ${exitStrategy.profitTarget.rule} *(stock at ${exitStrategy.profitTarget.stockPrice})*`,
    `- 🔴 **Stop loss:** ${exitStrategy.stopLoss.rule} *(stock at ${exitStrategy.stopLoss.stockPrice})*`,
    `- 🕐 **Time stop:** ${exitStrategy.timeStop.rule} *(close by ${exitStrategy.timeStop.date})*`,
  );
  if (exitStrategy.earningsWarning) {
    lines.push(`- ⚠️ **Earnings:** ${exitStrategy.earningsWarning}`);
  }

  lines.push(
    "",
    "## Greeks",
    `- **Δ Delta ${greeks.delta.value}:** ${greeks.delta.insight}`,
    `- **Θ Theta ${greeks.theta.value}:** ${greeks.theta.insight}`,
    `- **Γ Gamma ${greeks.gamma.value}:** ${greeks.gamma.insight}`,
    `- **ν Vega ${greeks.vega.value}:** ${greeks.vega.insight}`,
    `- **IV rank:** ${greeks.ivRankInsight}`,
    "",
    "## Scenarios",
    "| | Bull | Base | Bear |",
    "|---|---|---|---|",
    `| Probability | ${predictions.bullCase.probability} | ${predictions.baseCase.probability} | ${predictions.bearCase.probability} |`,
    `| Option return | ${predictions.bullCase.optionReturn} | ${predictions.baseCase.optionReturn} | ${predictions.bearCase.optionReturn} |`,
    `| Stock target | ${predictions.bullCase.stockTarget} | ${predictions.baseCase.stockTarget} | ${predictions.bearCase.stockTarget} |`,
    "",
    "## Rationale",
    rationale,
  );

  if (riskFactors?.length) {
    lines.push("", "## Risk factors");
    riskFactors.forEach(f => lines.push(`- ${f}`));
  }

  if (watchFor?.keyDates?.length) {
    lines.push("", "## Key dates");
    watchFor.keyDates.forEach(d => lines.push(`- **${d.date}** — ${d.event} *(${d.impact})*`));
  }

  if (marketContext) {
    lines.push("", "## Market context", marketContext);
  }

  lines.push(
    "",
    "---",
    "*Generated by [Options Advisor](https://options-advisor-sepia.vercel.app) — educational purposes only, not financial advice.*",
    "",
    "I received this options trade recommendation. Can you help me:",
    "1. Evaluate whether the timing and entry make sense right now",
    "2. Identify any risks or blind spots the analysis may have missed",
    "3. Suggest any adjustments to the strike, expiry, or strategy structure",
  );

  return lines.join("\n");
}
